language: 
   - java
   
version: 1.7
sudo: false
os: Windows10

services:
 - docker

before_script: cd /home/travis/build/SujataDarekar/NewMavenRepository/Source/bw6-maven-plugin
script:
 - mvn compile
 - mvn package
 
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
     - /home/travis/build/SujataDarekar/NewMavenRepository/Source/bw6-maven-plugin/target/bw6-maven-plugin-1.2.2.jar
  skip_cleanup: true
  on: 
  tags: false