language: 
   - java
   - ruby
   
version: 1.7
sudo: false
os: Windows10
#buildpath: HOME
services:
- docker
#env:
  # - HOME: "C:/Users/sdarekar"
   #- TRAVIS_BUILD_DIR: "D"

  #cache:
 # directories:
  #- "$HOME/.cache"

script:
 - mvn compile
 - mvn package
 - mvn "com.tibco.plugins:bw6-maven-plugin:Demo"

  
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
     - /home/travis/build/SujataDarekar/MavenPlugin/target/bw6-maven-plugin-1.2.2.jar
     - /home/travis/build/SujataDarekar/MavenPlugin/src/test/java/TIB_BW_Maven_Plugin_1.2.2.zip
  skip_cleanup: true
  on: 
  tags: false